### ISSUE TITLE
Markdown代码块bug

### ISSUE THREAD

**Issue by wZuck** [grace-note/grace-note#10]
在markdown模式下输入类似代码块
```cpp
#include <bits/stdc++.h>
```
这一行在编辑模式下会被认为是一级标题（#）

**Comment by yuankui** [comment]
@wZuck 明白，后面会修复~

**Comment by yuankui** [comment]
@wZuck 已经修复
https://github.com/grace-note/grace-note/releases/tag/v1.2.1

![image](https://user-images.githubusercontent.com/236535/81373088-7bd06700-912e-11ea-92ed-fba9bd009f8d.png)
