### ISSUE TITLE
不支持ssh的远程链接吗

### ISSUE THREAD

**Issue by aitsc** [grace-note/grace-note#11]
push errorUnknownTransportError: Git remote "git@github.com:xxx/xxx.git" uses an unrecognized transport protocol: "ssh"

**Comment by yuankui** [comment]
@aitsc 正在开发中，五一后会发布新的版本

**Comment by yuankui** [comment]
@aitsc 
https://github.com/grace-note/grace-note/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E4%BB%A4
