### ISSUE TITLE
有任何计划试试在项目内使用 ZEIT-UI 吗

### ISSUE THREAD

**Issue by unix** [grace-note/grace-note#7]
这个项目非常酷 👍

我推荐一个 React 组件库 [ZEIT React](https://github.com/zeit-ui/react)，它可以帮助 Grace 在一些文本排版时做的更好，当然您也可以选择只使用部分的组件。建议尝试一下，一起丰富 Grace Note ！🎉🎉

**Comment by liangshuai** [comment]
你这广告打的

**Comment by yuankui** [comment]
@unix 这个组件库我之前在v站看到过，非常简洁，我个人还是比较从崇尚简洁的。

比如它的Toast组件我就非常喜欢，非常乐意在后续的版本中替换掉antd的message.info()

另外顺提一下，tabs可以支持垂直方向的吗？

**Comment by unix** [comment]
@yuankui 
暂时不支持，组件库现在还是 follow design 的状态，离功能丰富、大而全还有很长的路。
不过可以考虑一些基础排版、文字或是基础样式，这些组件的设计和易用性都非常不错。

谢谢关注，先关闭 Issue 了。
